2021-03-08 00:03:15.894290: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/gdrcopy/lib64:/usr/gdcropy/include:/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:/usr/local/openmpi/lib:/usr/local/magma/lib:/usr/local/magma/include
2021-03-08 00:03:15.894330: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "program_tesis_luthfil.py", line 59, in <module>
    data_aspek = pd.read_csv(path_data_aspek, sep=";", header=[0], encoding="UTF-8")
  File "/home/m433782/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/m433782/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/m433782/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/m433782/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/m433782/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1993, in __init__
    src = open(src, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/Thesis/Tesis/program/data/dataset/dataset_aspek.csv'
srun: error: komputasi03: task 0: Exited with exit code 1
